PL_MVC/Controllers/SucursalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PL_MVC.Controllers
{
    public class SucursalController : Controller
    {
        // GET: Sucursal
        [HttpGet]
        public ActionResult GeAllS()
        {
            ML.Sucursal sucursal = new ML.Sucursal();
            ML.Result result = BL.Sucursal.GetAllEF();

            if (result.Correct)
            {
                sucursal.Sucursales = result.Objects;
            }
            else
            {
                ViewBag.MensajeError = "No se encontraron registros " + result.ErrorMessage;
            }

            return View("GeAllS", sucursal);
        }

        [HttpPost]
        public ActionResult GeAllS(ML.Sucursal sucursal)
        {
            
            ML.Result result = BL.Sucursal.GetAllEF();

            if (result.Correct)
            {
                sucursal.Sucursales = result.Objects;
            }
            else
            {
                ViewBag.MensajeError = "No se encontraron registros " + result.ErrorMessage;
            }

            return View("GeAllS", sucursal);
        }

        [HttpGet]
        public ActionResult Form(int? IdSucursal)
        {
            ML.Sucursal sucursal = new ML.Sucursal();

            ML.Result resultSucursal = BL.Sucursal.GetAllEF();
            if (resultSucursal.Correct)
            {
                sucursal.Sucursales = resultSucursal.Objects;
            }
            

            if (IdSucursal != null) //UPDATE con GetById para que muestre los datos del form para actualizar
            {
                ML.Result result = BL.Sucursal.GetByIdEF(IdSucursal.Value);
                if (result.Correct)
                {
                    sucursal = (ML.Sucursal)result.Object;
                    if (resultSucursal.Correct)
                    {
                        sucursal.Sucursales = resultSucursal.Objects;
                    }
                }
                else
                {
                    ViewBag.MensajeError = "Ocurrió un error al obtener la información del producto.";
                }
            }

            return View(sucursal);
        }

        [HttpPost]
        public ActionResult Form(ML.Sucursal sucursal)
        {
            ML.Result result = new ML.Result();

            if(sucursal.IdSucursal == 0)
            {
                result = BL.Sucursal.AddEF(sucursal);

                if (result.Correct)
                {
                    ViewBag.Message = "El registro se ha agregado correctamente";
                }
                else
                {
                    ViewBag.Message = "Hubo un error a la hora de hacer el registro";
                }
            }
            else
            {
                if (sucursal.IdSucursal >= 0)
                {
                    result = BL.Sucursal.UpdateEF(sucursal); //Actualizar

                    if (result.Correct)
                    {
                        ViewBag.Message = "El registro se ha actualizo correctamente";
                    }
                    else
                    {
                        ViewBag.Message = "Hubo un error a la hora de hacer la actualizacion";
                    }
                }
            }

            return PartialView("Modal");
        }

        [HttpGet] //Eliminar
        public ActionResult Delete(int IdSucursal)
        {
            if(IdSucursal > 0)
            {
                ML.Result result = BL.Sucursal.DeleteEF(IdSucursal);

                if (result.Correct)
                {
                    ViewBag.Message = "El registro se ha eliminado correctamente";
                }
                else
                {
                    ViewBag.Message = "Hubo un error a la hora de hacer la eliminación";
                }
            }
            else
            {
                ViewBag.Message = "IdProducto no es válido.";
            }

            return PartialView("Modal");
        }
    }
}

PL_MVC/Views/Sucursal/Form.cshtml
@model ML.Sucursal
@{
    ViewBag.Title = "Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-12">
            <h2 class="text-center">Registro de una nueva Sucursal</h2>
            <center><h5> Formulario para el ingreso de una nueva Sucursal.</h5></center>
            <hr />
        </div>
    </div>

    <div class="row">
        <div class="col-4">
            @using (Html.BeginForm("Form", "Sucursal", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {

                @*@html.labelfor(model => model.idsucursal, new { @class = "form-label" })*@
                @Html.TextBoxFor(model => model.IdSucursal, "{0:#.#}", new { @class = "form-control", type = "hidden" })
                <br />
                @Html.LabelFor(model => model.Nombre, new { @class = "form-label" })
                @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control", placeholder = "Ingrese Nombre de la Sucursal", id = "Nombre", @onkeypress = "ValidarNombre(event)" })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                <br />
                @Html.LabelFor(model => model.Latitud, new { @class = "form-label" })
                @Html.TextBoxFor(model => model.Latitud, new { @class = "form-control", placeholder = "Ingrese Latitud", id = "latitud", @readonly = "readonly" })
                <br />
                @Html.LabelFor(model => model.Longitud, new { @class = "form-label" })
                @Html.TextBoxFor(model => model.Longitud, new { @class = "form-control", placeholder = "Ingrese Longitud", id = "longitud", @readonly = "readonly" })
                <br />
                <br />
                <div class="text-center">
                    <button type="submit" class="btn btn-success">Guadar</button>

                    @Html.ActionLink("Regresar", "GeAllS", "Sucursal", new { @class = "btn btn-danger" })
                </div>

            }
        </div>

        <div class="col-8">
            <div id="map" style="height: 400px; width: 600px;"></div>

            <script async src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCSKBDdPPlfca_zTwyxKiicRQn1qfgRjLw&callback=initMap&libraries=places" defer></script>

            <script>
                //let coordenadas = { lat: @Model.Latitud, lng: @Model.Longitud }; Me permite tener la coordenada exacta de mi registro.
                //let coordenadas = { lat: 19.430482044483313, lng: -99.16163406195687 }; Me permite tener la coordenada exacta de "Digis01".
                let coordenadas = {
                    lat: @(string.IsNullOrEmpty(Model.Latitud) ? 19.430482044483313 : Convert.ToDouble(Model.Latitud)),
                    lng: @(string.IsNullOrEmpty(Model.Longitud) ? -99.16163406195687 : Convert.ToDouble(Model.Longitud))
                };
                let map;
                let marcador;
                let infoWindow;

                function initMap() {
                    const mapDiv = document.getElementById("map");
                    map = new google.maps.Map(mapDiv, {
                        center: coordenadas,
                        zoom: 15,
                    });

                    infoWindow = new google.maps.InfoWindow();

                    marcador = new google.maps.Marker({
                        position: coordenadas,
                        map: map,
                        draggable: true // Poder hacer que el Marvador se mueva donde sea
                    });

                    // Escuchar el evento dragend (evento que arrastra sobre un elemento o texto selecionado)
                    marcador.addListener('dragend', function (event) {
                        const position = {
                            lat: event.latLng.lat(),
                            lng: event.latLng.lng()
                    };

                        // Se actulizaran las coordenadas en los texbox dependiendo de donde se mueva el Marcador
                        document.getElementById('latitud').value = position.lat.toFixed(6);
                        document.getElementById('longitud').value = position.lng.toFixed(6);

                        // Mostrara y Actualizar la informacion entre el InfoWindow 
                        infoWindow.setContent(`Latitud: ${position.lat.toFixed(6)}, <br/> Longitud: ${position.lng.toFixed(6)}`);
                        infoWindow.setPosition(position);
                        infoWindow.open(map);
                    });

                    // Para ver el InfoWindow, hacemos clic en el marcador
                    marcador.addListener('click', function () {
                        const position = {
                            lat: marcador.getPosition().lat(),
                            lng: marcador.getPosition().lng()
                    };

                        // Actualizar las coordenadas en los TextBox
                        document.getElementById('latitud').value = position.lat.toFixed(6);
                        document.getElementById('longitud').value = position.lng.toFixed(6);

                        infoWindow.setContent(`Marcador en: ${position.lat.toFixed(6)}, ${position.lng.toFixed(6)}`);
                        infoWindow.setPosition(position);
                        infoWindow.open(map);
                    });
                }
            </script>
        </div>

        @section Scripts{
            @Scripts.Render("~/bundles/jqueryval")
        }

        <script src="~/Scripts/jquery-3.4.1.js"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
        <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

        <style>
            input.valid {
                border-color: green;
            }

            input.invalid {
                border-color: red;
            }
        </style>

        <script>
            function ValidarNombre(event) {
                var nombre = String.fromCharCode(event.charCode); //Convt ccaracter ing a r
                var expRe = /^[A-Za-z\s\.]+$/;

                if (!expRe.test(nombre)) { //ev ci
                    event.preventDefault();
                    return false;
                }
                return true;
            }

            $('#Nombre').bind("cut copy paste", function (e) {
                e.preventDefault();
            });
        </script>

    </div>
</div>

@* apiKey Google Maps = <script async src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCSKBDdPPlfca_zTwyxKiicRQn1qfgRjLw&callback=initMap&libraries=places"></script>*@

PL_MVC/Views/Sucursal/GeAllS.cshtml
@model ML.Sucursal
@{
    ViewBag.Title = "GeAllS";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <h3 class="text-center">Sucursales</h3>
        <hr />
    </div>

    <div class="row">
        <div class="col-12 mb-4 text-center">
            <a href="@Url.Action("Form", "Sucursal")" class="btn btn-primary">
                <i class="bi bi-shop"></i>
                Agregar Sucursal
            </a>
        </div>
    </div>

    <div class="row">
        <div class="col-6">
            <div class="table-responsive">
                @if (Model.Sucursales != null)
                {
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>Nombre</th>
                                <th>Latitud</th>
                                <th>Longitud</th>
                                <th>Editar</th>
                                <th>Eliminar</th>
                            </tr>
                        </thead>

                        <tbody>
                            @foreach (ML.Sucursal sucursal in Model.Sucursales)
                            {
                                <tr>

                                    <td>@sucursal.Nombre</td>
                                    <td>@sucursal.Latitud</td>
                                    <td>@sucursal.Longitud</td>
                                    <td>
                                        <a class="btn btn-warning" href="@Url.Action("Form","Sucursal", new { IdSucursal = sucursal.IdSucursal })"> <i class="bi bi-pencil-square"></i> </a>
                                    </td>
                                    <td>
                                        <a class="btn btn-danger" href="@Url.Action("Delete", "Sucursal",  new { IdSucursal = sucursal.IdSucursal })"
                                           onclick="return confirm('¿Desea eliminar esta Sucursal?')">
                                            <i class="bi bi-trash-fill"></i>
                                        </a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                }
                else
                {
                    <div class="alert alert-danger" role="alert">
                        @ViewBag.MensajeError
                    </div>
                }

            </div>
        </div>

        <div class="col-6">
            <div id="map" style="height: 470px; width: 600px;"></div>
            <script async src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCSKBDdPPlfca_zTwyxKiicRQn1qfgRjLw&callback=initMap&libraries=places" defer></script>
            <script>
                let map;
                let infoWindow;

                // Se crea un array para traer las sucursales que 
                const sucursales = [
                    @if (Model.Sucursales != null && Model.Sucursales.Any())
                    {
                        foreach (ML.Sucursal sucursal in Model.Sucursales)
                        {
                            <text>{ lat: @sucursal.Latitud, lng: @sucursal.Longitud, nombre: '@sucursal.Nombre' },</text>
                        }
                    }
                ];

                function initMap() {
                    const mapDiv = document.getElementById("map");
                    const bounds = new google.maps.LatLngBounds(); // Creacion de objeto LatLngBounds

                    map = new google.maps.Map(mapDiv, {
                        center: { lat: 19.430482044483313, lng: -99.16163406195687 }, // Punto Central al ejecutar
                       //zoom = 7         
                    });

                    infoWindow = new google.maps.InfoWindow();

                    // Se crean marcadores para cada Sucursal
                    sucursales.forEach(sucursal => {
                        const position = { lat: sucursal.lat, lng: sucursal.lng };
                        const marker = new google.maps.Marker({
                            position: position,
                            map: map,
                            title: sucursal.nombre
                        });

                        // Extendemos los límites del mapa para incluir cada sucursal
                        bounds.extend(position);

                        
                        /*marker.addListener('click', () => {
                            infoWindow.setContent(sucursal.nombre);
                            infoWindow.open(map, marker);
                        });*/
                        // Abrir InfoWindow al hacer clic en el marcador
                        marker.addListener('click', () => {
                            // Muestra el nombre, latitud y longitud
                            const contentString = `
                                <div>
                                    <strong>Sucursal: </strong> ${sucursal.nombre} <br>
                                    <strong>Latitud: </strong> ${sucursal.lat} <br>
                                    <strong>Longitud: </strong> ${sucursal.lng} <br>
                                </div>
                            `;

                            // Establecer el contenido del InfoWindow
                            infoWindow.setContent(contentString);
                            infoWindow.open(map, marker);
                        });
                    
                    });

                    // Ajustar el mapa para mostrar todos los marcadores
                    map.fitBounds(bounds);
                }

            </script>
        </div>

        @*<div class="col-6">
            <div id="map" style="height: 470px; width: 600px;"></div>
            <script async src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCSKBDdPPlfca_zTwyxKiicRQn1qfgRjLw&callback=initMap&libraries=places"></script>
            <script>
                let coordenadas = { lat: 19.430482044483313, lng: -99.16163406195687 };
                let map;
                let marcador;

                function initMap() {
                    const mapDiv = document.getElementById("map");
                    map = new google.maps.Map(mapDiv, {
                        center: coordenadas,
                        zoom: 17,
                    });
                    marcador = new google.maps.Marker({
                        position: coordenadas,
                        map: map,
                    });
                }
            </script>
        </div>*@

    </div>

</div>

PL_MVC/Views/Sucursal/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="Modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Message</h5>
            </div>
            <div class="modal-footer">
                @Html.ActionLink("Entendido", "GeAllS", "Sucursal", new { area = "" }, htmlAttributes: new { @class = "btn btn-danger" })

            </div>
        </div>
    </div>
</div>

<script>$('#Modal').modal();</script>