PL_MVC/Controllers/ProductoSucursalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;

namespace PL_MVC.Controllers
{
    public class ProductoSucursalController : Controller
    {
        // GET: ProductoSucursal

        [HttpGet]
        public ActionResult GetAllPS()
        {
            ML.ProductoSucursal productoSucursal = new ML.ProductoSucursal();
            productoSucursal.Sucursal = new ML.Sucursal();
            productoSucursal.Sucursal.IdSucursal = 0;

            ML.Result result = BL.ProductoSucursal.GetAllEF(productoSucursal.Sucursal.IdSucursal);

            if (result.Correct)
            {
                productoSucursal.ProductosSucursales = result.Objects;
            }
            else
            {
                ViewBag.MensajeError = "No se encontraron registros" + result.ErrorMessage;
            }

            
            productoSucursal.Sucursal = new ML.Sucursal();
            ML.Result resultSucursal = BL.Sucursal.GetAllEF();

            if (resultSucursal.Correct)
            {
                productoSucursal.Sucursal.Sucursales = resultSucursal.Objects;

            }
            else
            {
                productoSucursal.Sucursal.Sucursales = new List<object>();
            }

            ViewBag.Sucursales = new SelectList(productoSucursal.Sucursal.Sucursales, "IdSucursal", "Nombre", productoSucursal.Sucursal.IdSucursal);

            return View(productoSucursal);
        }

        [HttpPost]
        public ActionResult GetAllPS(ML.ProductoSucursal productoSucursal)
        {
            productoSucursal.Sucursal.IdSucursal = productoSucursal.Sucursal.IdSucursal !=0 ? productoSucursal.Sucursal.IdSucursal : 0;

            ML.Result result = BL.ProductoSucursal.GetAllEF(productoSucursal.Sucursal.IdSucursal);

            if (result.Correct)
            {
                productoSucursal.ProductosSucursales = result.Objects;
            }
            else
            {
                ViewBag.MensajeError = "No se encontraron registros" + result.ErrorMessage;
            }

            productoSucursal.Sucursal = new ML.Sucursal();
            ML.Result resultSucursal = BL.Sucursal.GetAllEF();

            if (resultSucursal.Correct)
            {
                productoSucursal.Sucursal.Sucursales = resultSucursal.Objects;
            }
            else
            {
                productoSucursal.Sucursal.Sucursales = new List<object>();
            }

            ViewBag.Sucursales = new SelectList(productoSucursal.Sucursal.Sucursales, "IdSucursal", "Nombre", productoSucursal.Sucursal.IdSucursal);

            return View(productoSucursal);
        }

        [HttpPost]
        public ActionResult UpdatePS(int IdProductoSucursal, int Stock)
        {
            ML.ProductoSucursal productoSucursal = new ML.ProductoSucursal();
            productoSucursal.IdProductoSucursal = IdProductoSucursal;
            productoSucursal.Stock = Stock;

            ML.Result result = BL.ProductoSucursal.UpdateEF(productoSucursal);

            if (result.Correct)
            {
                ViewBag.Message = "El Stock se actualizó correctamente";
            }
            else
            {
                ViewBag.ErrorMessage = result.ErrorMessage;
                return View("Error");
            }
            return PartialView("Modal");
        }

        [HttpGet]
        public ActionResult DeletePS(int IdProductoSucursal)
        {
            ML.ProductoSucursal productoSucursal = new ML.ProductoSucursal { IdProductoSucursal = IdProductoSucursal };

            ML.Result result = BL.ProductoSucursal.DeleteEF(IdProductoSucursal);

            if (result.Correct)
            {
                ViewBag.Message = "El registro se eliminó correctamente.";
            }
            else
            {
                ViewBag.MensajeError = "No se pudo eliminar: " + result.ErrorMessage;
            }

            return PartialView("Modal");
        }

        /*[HttpPost]
        public ActionResult UpdatePS(int IdProductoSucursal, int Stock)
        {
            ML.ProductoSucursal productoSucursal = new ML.ProductoSucursal();
            productoSucursal.IdProductoSucursal = IdProductoSucursal;
            productoSucursal.Stock = Stock;

            ML.Result result = BL.ProductoSucursal.UpdateEF(productoSucursal);

            if (result.Correct)
            {
                ViewBag.Message = "El Stock se actualizo correctamente";
            }
            else
            {
                ViewBag.ErrorMessage = result.ErrorMessage;
                return View("Error");
            }
            return PartialView("Modal");
        }*/

        /* [HttpGet]
         public ActionResult GetAllPS()
         {
             ML.ProductoSucursal productoSucursal = new ML.ProductoSucursal();
             ML.Result resultSucursal = BL.Sucursal.GetAllEF();

             if (resultSucursal.Correct)
             {
                 productoSucursal.Sucursal = new ML.Sucursal();
                 productoSucursal.Sucursal.Sucursales = resultSucursal.Objects;
                 productoSucursal.Sucursal.IdSucursal = -1;
             }
             else
             {
                 ViewBag.MensajeError = "No se encontraron registros " + resultSucursal.ErrorMessage;
             }

             ML.Result resultProductos = BL.ProductoSucursal.GetAllEF();

             if (resultProductos.Correct)
             {
                 productoSucursal.ProductosSucursales = resultProductos.Objects;
             }
             else
             {
                 ViewBag.MensajeError = "No se encontraron registros " + resultProductos.ErrorMessage;
             }

             return View(productoSucursal);
         }

         [HttpPost]
         public ActionResult GetAllPS(ML.ProductoSucursal productosucursal)
         {
             if (productosucursal.Sucursal != null && productosucursal.Sucursal.IdSucursal > 0)
             {
                 ML.Result resultSucursal = BL.ProductoSucursal.GetByIdSucursalEF(productosucursal.Sucursal.IdSucursal);

                 if (resultSucursal.Correct)
                 {
                     productosucursal.ProductosSucursales = resultSucursal.Objects;
                 }
             }
             else
             {
                 ML.Result resultAllSucursales = BL.ProductoSucursal.GetAllEF();

                 if (resultAllSucursales.Correct)
                 {
                     productosucursal.ProductosSucursales = resultAllSucursales.Objects;
                 }
                 else
                 {
                     ViewBag.MensajeError = "No se encontraron registros " + resultAllSucursales.ErrorMessage;
                 }
             }

             ML.Result resultSucursales = BL.Sucursal.GetAllEF();

             if (resultSucursales.Correct)
             {
                 productosucursal.Sucursal.Sucursales = resultSucursales.Objects;
             }

             return View(productosucursal);

         }*/

        /*[HttpPost]
        public ActionResult UpdatePS(int IdProductoSucursal, int Stock)
        {
            ML.ProductoSucursal productoSucursal = new ML.ProductoSucursal();
            productoSucursal.IdProductoSucursal = IdProductoSucursal;
            productoSucursal.Stock = Stock;

            ML.Result resultUpdate = BL.ProductoSucursal.UpdateEF(productoSucursal);

            if (resultUpdate.Correct)
            {
                ViewBag.Message = "El Stock se actualizo correctamente";
            }
            else
            {
                ViewBag.ErrorMessage = resultUpdate.ErrorMessage;
                return View("Error");
            }
            return PartialView("Modal");
        }*/

        /*[HttpPost]
        public ActionResult UpdatePS(int IdProductoSucursal, int Stock)
        {
            // Obtener el objeto ProductoSucursal por su Id
            ML.Result result = BL.ProductoSucursal.GetByIdEF(IdProductoSucursal);

            if (result.Correct)
            {
                ML.ProductoSucursal productoSucursal = (ML.ProductoSucursal)result.Object;  // Obtén el objeto ProductoSucursal

                // Actualiza el stock
                //productoSucursal.Stock = Stock;

                // Llama al método de actualización en la capa de negocio
                ML.Result resultUpdate = BL.ProductoSucursal.UpdateEF(productoSucursal);

                if (resultUpdate.Correct)
                {
                    ViewBag.Message = "El Stock se actualizó correctamente";
                    return PartialView("Modal"); // Modal con mensaje de éxito
                }
                else
                {
                    ViewBag.ErrorMessage = resultUpdate.ErrorMessage;
                    return View("Error"); // Vista de error en caso de fallo en la actualización
                }
            }
            else
            {
                ViewBag.ErrorMessage = result.ErrorMessage;
                return View("Error"); // Vista de error si no se encuentra el ProductoSucursal
            }
            return PartialView("Modal");
        }*/



    }
}

PL_MVC/Views/ProductoSucursal/GetAllPS.cshtml
@model ML.ProductoSucursal
@{
    ViewBag.Title = "GetAllPS";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="row">
            <h2 class="text-center">GETALL Productos - Sucursales</h2>
            <h5 class="text-center">Asignacion de productos con sus Sucursales, estableciendo la relacion que ambos comparten. </h5>
            <hr />
        </div>
    </div>

    <div id="busqueda">
        <div class="row">
            <h5>Seleccionar la Sucursal para consultar los productos. </h5>
            @using (Html.BeginForm("GetAllPS", "ProductoSucursal", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <div class="col-4 d-flex justify-content-between">
                    <div class="col-md-8">
                        @*@Html.LabelFor(model => model.Sucursal, new { @class = "form-label" })*@
                        @Html.DropDownListFor(model => model.Sucursal.IdSucursal, new SelectList(Model.Sucursal.Sucursales, "IdSucursal", "Nombre"), "---Selecciona una Sucursal---", new { @class = "form-control" })
                    </div>

                    <div class="col-md-2 text-right">
                        <button type="submit" class="btn btn-success">Buscar</button>
                    </div>
                </div>
            }
        </div>
    </div>
    <hr />

    <div class="row">
        <div class="table-responsive">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Editar</th>
                        <th>Imagen</th>
                        <th>Producto</th>
                        <th>Sucursal</th>
                        <th>Stock</th>
                        <th>Guardar</th>
                        <th>Eliminar</th>
                    </tr>
                </thead>

                <h3>Productos que pertenen a la sucursal</h3>
                <tbody>
                    @foreach (ML.ProductoSucursal productoSucursal in Model.ProductosSucursales)
                    {
                        <tr>
                            @*<td>
                                    <a href="javascript:void(0);" onclick="habilitarStock(@productoSucursal.IdProductoSucursal);">
                                        <button class="btn btn-warning">Editar</button>
                                    </a>
                                </td>*@
                            <td>
                                <a href="javascript:void(0);" onclick="habilitarStock(@productoSucursal.IdProductoSucursal);">
                                    <button id="btnEditarCancelar_@productoSucursal.IdProductoSucursal" class="btn btn-warning">
                                        Editar
                                    </button>
                                </a>

                            </td>

                            <td>
                                @if (productoSucursal.Producto.Imagen == null)
                                {
                                    <img id="img" src="~/Content/img/Default2.jpg" width="70" height="70" />
                                }
                                else
                                {
                                    <img id="img" src="data:image/png;base64,@Convert.ToBase64String(productoSucursal.Producto.Imagen)" width="70" height="70" />
                                }
                            </td>
                            <td>@productoSucursal.Producto.Nombre</td>
                            <td>@productoSucursal.Sucursal.Nombre</td>

                            <form action="@Url.Action("UpdatePS", "ProductoSucursal")" method="post">

                                <input type="hidden" name="IdProductoSucursal" value="@productoSucursal.IdProductoSucursal" />

                            <td>
                                <div>
                                    <input class="form-control" id="stockInput_@productoSucursal.IdProductoSucursal" name="Stock" type="number"
                                           value="@productoSucursal.Stock" placeholder="Sin stock disponible" disabled>

                                </div>
                            </td>

                            <td>
                                <button type="submit" class="btn btn-primary">
                                    Guardar
                                </button>
                            </td>
                            <td>
                                <a href="@Url.Action("DeletePS", "ProductoSucursal", new { IdProductoSucursal = productoSucursal.IdProductoSucursal })"
                                   onclick="return confirm('¿Estás seguro que deseas eliminar?')">
                                    <button type="button" class="btn btn-danger"><i class="bi bi-trash3-fill"></i></button>
                                </a>
                            </td>



                            </form>
                        </tr>
                    }

                </tbody>
            </table>

        </div>
    </div>
</div>

<script src="~/Scripts/jquery-3.4.1.js"></script>
<script>
    /*function habilitarStock(idProductoSucursal) {
        var stockInput = document.getElementById('stockInput_' + idProductoSucursal);
        if (stockInput) {
            stockInput.disabled = false; // Habilita el input
        }
    }*/

    function habilitarStock(idProductoSucursal) {
        var stockInput = document.getElementById('stockInput_' + idProductoSucursal);
        var btnEditarCancelar = document.getElementById('btnEditarCancelar_' + idProductoSucursal);

        if (stockInput.disabled) {
            // Si el input está deshabilitado, habilitarlo y cambiar el texto del botón
            stockInput.disabled = false;
            btnEditarCancelar.textContent = 'Cancelar';
            btnEditarCancelar.classList.remove('btn-warning');
            btnEditarCancelar.classList.add('btn-secondary');
        } else {
            // Si el input está habilitado, deshabilitarlo y cambiar el texto del botón
            stockInput.disabled = true;
            btnEditarCancelar.textContent = 'Editar';
            btnEditarCancelar.classList.remove('btn-danger');
            btnEditarCancelar.classList.add('btn-warning');
        }
    }


</script>

@*<head>
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
        <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
        <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    </head>*@

@*<div class="container">
        <div class="row">
            <h2 class="text-center">GETALL Productos - Sucursales</h2>
            <h5 class="text-center">Asignacion de productos con sus Sucursales, estableciendo la relacion que ambos comparten. </h5>
            <hr />
        </div>

        <div class="row">
            <div class="col-12">
                <h5>Seleccionar la Sucursal para consultar los productos. </h5>
                @using (Html.BeginForm("GetAllPS", "ProductoSucursal", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.DropDownListFor(model => model.Sucursal.IdSucursal, new SelectList(Model.Sucursal.Sucursales, "IdSucursal", "Nombre", -1), "--- Selecciona una Sucursal ---", new { @class = "form-control" })
                }
                <br />
                <button type="submit" class="btn btn-success">Buscar</button>
                <br />
            </div>

            <hr />
        </div>



        <div class="row">
            <div class="table-responsive">
                @if (Model.ProductosSucursales != null && Model.ProductosSucursales.Count > 0)
                {
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>Editar</th>
                                <th>Imagen</th>
                                <th>Producto</th>
                                <th>Sucursal</th>
                                <th>Stock</th>
                                <th>Eliminar</th>
                            </tr>
                        </thead>

                        <h3>Productos que pertenen a la sucursal</h3>
                        <tbody>
                            @foreach (ML.ProductoSucursal productoSucursal in Model.ProductosSucursales)
                            {
                                <tr>
                                    <td>
                                        <a class="btn btn-warning" href="@Url.Action("Form","ProductoSucursal", new { IdProductoSucursal = productoSucursal.IdProductoSucursal })"> Editar </a>
                                    </td>
                                    <td>
                                        @if (productoSucursal.Producto.Imagen == null)
                                        {
                                            <img id="img" src="~/Content/Img/Img_DefaultProduct.png" width="100" height="100" />
                                        }
                                        else
                                        {
                                            <img id="img" src="data:image/png;base64,@Convert.ToBase64String(productoSucursal.Producto.Imagen)" width="100" height="100" />
                                        }
                                    </td>
                                    <td>@productoSucursal.Producto.Nombre</td>
                                    <td>@productoSucursal.Sucursal.Nombre</td>
                                    <td>
                                        <input type="text" name="Stock" value="@productoSucursal.Stock" />
                                    </td>
                                    <td>
                                        <a class="btn btn-primary" href="@Url.Action("Form","ProductoSucursal", new { IdProductoSucursal = productoSucursal.IdProductoSucursal })"> Guardar</a>
                                        <a class="btn btn-danger" href="@Url.Action("Form","ProductoSucursal", new { IdProductoSucursal = productoSucursal.IdProductoSucursal })"> <i class="bi bi-trash-fill"></i></a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                }
                else
                {
                    <div class="alert alert-danger" role="alert">
                        @ViewBag.MensajeError
                    </div>
                }
            </div>
        </div>
    </div>*@

PL_MVC/Views/ProductoSucursal/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="Modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Message</h5>
            </div>
            <div class="modal-footer">
                @Html.ActionLink("Entendido", "GetAllPS", "ProductoSucursal", new { area = "" }, htmlAttributes: new { @class = "btn btn-danger" })

            </div>
        </div>
    </div>
</div>

<script>$('#Modal').modal();</script>