PL_MVC/Controllers/RepartidorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PL_MVC.Controllers
{
    public class RepartidorController : Controller
    {
        // GET: Repartidor
        [HttpGet]
        public ActionResult GetAllRep()
        {
            ML.Repartidor repartidor = new ML.Repartidor();

            ML.Result result = BL.Repartidor.GetAllEF();

            if (result.Correct)
            {
                repartidor.Repartidores = result.Objects;
            }
            else
            {
                ViewBag.MensajeError = "No se encontraron registros " + result.ErrorMessage;
            }

            return View("GetAllRep", repartidor);
        }

        [HttpPost]
        public ActionResult GetAllRep(ML.Repartidor repartidor)
        {
            ML.Result result = BL.Repartidor.GetAllEF();

            if (result.Correct)
            {
                repartidor.Repartidores = result.Objects;
            }
            else
            {
                ViewBag.MensajeError = "No se encontraron registros " + result.ErrorMessage;
            }

            return View("GetAllRep", repartidor);
        }

        [HttpGet]
        public ActionResult Form(int? IdRepartidor)
        {
            ML.Repartidor repartidor = new ML.Repartidor();

            ML.Result resultRepartidor = BL.Repartidor.GetAllEF();
            if (resultRepartidor.Correct)
            {
                repartidor.Repartidores = resultRepartidor.Objects;
            }

            if(IdRepartidor != null)
            {
                ML.Result result = BL.Repartidor.GetByIdEF(IdRepartidor.Value);
                if (result.Correct)
                {
                    repartidor = (ML.Repartidor)result.Object;
                    if (resultRepartidor.Correct)
                    {
                        repartidor.Repartidores = resultRepartidor.Objects;
                    }
                }
                else
                {
                    ViewBag.MensajeError = "Ocurrió un error al obtener la información del producto.";
                }
            }

            return View(repartidor);
        }

        [HttpPost]
        public ActionResult Form(ML.Repartidor repartidor)
        {
            ML.Result result = new ML.Result();

            if (repartidor.IdRepartidor == 0)
            {
                result = BL.Repartidor.AddEF(repartidor);

                if (result.Correct)
                {
                    ViewBag.Message = "El registro se ha agregado correctamente";
                }
                else
                {
                    ViewBag.Message = "Hubo un error a la hora de hacer el registro";
                }
            }
            else
            {
                if(repartidor.IdRepartidor >= 0)
                {
                    result = BL.Repartidor.UpdateEF(repartidor);
                    if (result.Correct)
                    {
                        ViewBag.Message = "El registro se ha actualizo correctamente";
                    }
                    else
                    {
                        ViewBag.Message = "Hubo un error a la hora de hacer la actualizacion";
                    }
                }
            }

            return View("Modal");
        }

        [HttpGet]
        public ActionResult Delete(int IdRepartidor)
        {
            if(IdRepartidor > 0)
            {
                ML.Result result = BL.Repartidor.DeleteEF(IdRepartidor);

                if (result.Correct)
                {
                    ViewBag.Message = "El registro se ha eliminado correctamente";
                }
                else
                {
                    ViewBag.Message = "Hubo un error a la hora de hacer la eliminación";
                }
            }
            else
            {
                ViewBag.Message = "IdRepartidor no es válido.";
            }

            return View("Modal");
        }
    }
}

PL_MVC/Views/Repartidor/Form.cshtml
@model ML.Repartidor
@{
    ViewBag.Title = "Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="col-12">
        <h2 class="text-center">Registro de un nuevo Repartidor</h2>
        <h5 class="text-center"> Formulario para el ingreso de un nuevo Repartidor y cargarlo al sistema.</h5>
        <hr />
    </div>

    <div class="row">
        <div class="col-4">
            @using (Html.BeginForm("Form", "Repartidor", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @* @Html.LabelFor(model => model.IdRepartidor, new { @class = "form-label" })*@
                @Html.TextBoxFor(model => model.IdRepartidor, "{0:#.#}", new { @class = "form-control", type = "hidden" })
                <br />
                @Html.LabelFor(model => model.Nombre, new { @class = "form-label" })
                @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control", @id = "Nombre", @onkeypress = "ValidarNombre(event)" })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                <br />
                @Html.LabelFor(model => model.ApellidoPaterno, new { @class = "form-label" })
                @Html.TextBoxFor(model => model.ApellidoPaterno, new { @class = "form-control", @id = "ApellidoPaterno", @onkeypress = "ValidarApellidoPaterno(event)" })
                @Html.ValidationMessageFor(model => model.ApellidoPaterno, "", new { @class = "text-danger" })

                <br />
                @Html.LabelFor(model => model.ApellidoMaterno, new { @class = "form-label" })
                @Html.TextBoxFor(model => model.ApellidoMaterno, new { @class = "form-control", @id = "ApellidoMaterno", @onkeypress = "ValidarApellidoMaterno(event)" })
                @Html.ValidationMessageFor(model => model.ApellidoMaterno, "", new { @class = "text-danger" })

                <br />
                <br />
                <div>
                    <button type="submit" class="btn btn-primary">Guadar Repartidor</button>
                    @Html.ActionLink("Regresar", "GetAllRep", "Repartidor", new { @class = "btn btn-danger" })
                </div>
            }
        </div>
    </div>
</div>

<style>
    input.valid {
        border-color: green;
    }

    input.invalid {
        border-color: red;
    }
</style>

<script src="~/Scripts/jquery-3.4.1.js"></script>

<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">


@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")
}

<script>
    $('#Nombre').bind("cut copy paste", function (e) {
        e.preventDefault();
    });

    $('#ApellidoPaterno').bind("cut copy paste", function (e) {
        e.preventDefault();
    });

    $('#ApellidoMaterno').bind("cut copy paste", function (e) {
        e.preventDefault();
    });
</script>

<script type="text/javascript">
    function ValidarNombre(event) {
        var nombre = String.fromCharCode(event.charCode); //Convt ccaracter ing a r
        var expRe = /^[A-Za-z\s\.]+$/;

        if (!expRe.test(nombre)) { //ev ci
            event.preventDefault();
            return false;
        }
        return true;
    }
    function ValidarApellidoPaterno(event) {
        var apellidoPaterno = String.fromCharCode(event.charCode);
        var expRe = /^[A-Za-zÁÉÍÓÚáéíóúÑñ\s\.]+$/; //   ^[A-Za-z\s\.]+$

        if (!expRe.test(apellidoPaterno)) {
            event.preventDefault();
            return false;
        }
        return true;
    }
    function ValidarApellidoMaterno(event) {
        var apellidoMaterno = String.fromCharCode(event.charCode);
        var expRe = /^[A-Za-zÁÉÍÓÚáéíóúÑñ\s\.]+$/;

        if (!expRe.test(apellidoMaterno)) {
            event.preventDefault();
            return false;
        }
        return true;
    }
</script>

PL_MVC/Views/Repartidor/GetAllRep.cshtml
@model ML.Repartidor
@{
    ViewBag.Title = "GetAllRep";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <h3 class="text-center">Repartidores</h3>
        <h5 class="text-center">Tabla con un registro de Repartidores almacenados en la base de datos.</h5>
        <hr />

    </div>

    <div class="row">
        <div class="col-12 text-center">
            <a href="@Url.Action("Form", "Repartidor")" class="btn btn-warning">
                <i class="bi bi-car-front" style="margin-right: 10px;"></i>
                Agregar Repartidor
            </a>
            <hr />
            
            
            <div class="table-responsive">
                @if(Model.Repartidores != null)
                {
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                @*<th>IdRepartidor</th>*@
                                <th>Nombre Repartidor</th>
                                <th>Apellido Paterno</th>
                                <th>Apellido Materno</th>
                                <th>Editar</th>
                                <th>Eliminar</th>
                            </tr>
                        </thead>

                        <tbody>
                            @foreach(ML.Repartidor Repartidor in Model.Repartidores)
                            {
                                <tr>
                                    @*<td>@Repartidor.IdRepartidor</td>*@
                                    <td>@Repartidor.Nombre</td>
                                    <td>@Repartidor.ApellidoPaterno</td>
                                    <td>@Repartidor.ApellidoMaterno</td>
                                    <td>
                                        <a class="btn btn-primary" href="@Url.Action("Form","Repartidor", new {  IdRepartidor = Repartidor.IdRepartidor })"> <i class="bi bi-pencil-square"></i> </a>
                                    </td>
                                    <td>
                                        <a class="btn btn-danger" href="@Url.Action("Delete", "Repartidor",  new { IdRepartidor = Repartidor.IdRepartidor })"
                                           onclick="return confirm('¿Desea eliminar este Repartidor?')">
                                            <i class="bi bi-person-x-fill"></i>
                                        </a>
                                    </td>
                                </tr>
                            }
                        </tbody>

                    </table>
                }
                else 
                {
                    <div class="alert alert-danger" role="alert">
                        @ViewBag.MensajeError
                    </div>
                }
            </div>
        </div>

    </div>
</div>

PL_MVC/Views/Repartidor/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="Modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Message</h5>
            </div>
            <div class="modal-footer">
                @Html.ActionLink("Entendido", "GetAllRep", "Repartidor", new { area = "" }, htmlAttributes: new { @class = "btn btn-danger" })

            </div>
        </div>
    </div>
</div>

<script>$('#Modal').modal();</script>